/**
 * What a fold rule merges: vocabulary pairs (each form seen ≥ 50 times in the
 * raw sources) that become identical under one rule, for review by hand.
 * Independent of UD.
 *
 *     node bench/collisions.ts                         # each normalization fold alone
 *     node bench/collisions.ts --diff fa-standard,h7-alef   # merges the second config adds over the first
 *
 * Writes bench/results/collisions.md (or collisions-<a>--<b>.md).
 */
import { writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { configByName } from "./configs.ts";
import { loadVocab } from "./vocab.ts";

const { values } = parseArgs({ options: { diff: { type: "string" }, min: { type: "string", default: "50" }, top: { type: "string", default: "60" } } });
const MIN = Number(values.min), TOP = Number(values.top);
const vocab = [...loadVocab()].filter(([, n]) => n >= MIN);

/** Each fold of src/normalize.ts, alone, as a plain string rule. */
const RULES: [string, (w: string) => string][] = [
  ["ي ى → ی", (w) => w.replace(/[يى]/g, "ی")],
  ["ك → ک", (w) => w.replaceAll("ك", "ک")],
  ["ة → ه", (w) => w.replaceAll("ة", "ه")],
  ["ۀ / ه\u0654 → ه", (w) => w.replaceAll("ۀ", "ه").replaceAll("ه\u0654", "ه")],
  ["أ إ ٱ → ا", (w) => w.replace(/[أإٱ]/g, "ا")],
  ["ؤ → و", (w) => w.replaceAll("ؤ", "و")],
  ["ئ → ی (H7, light)", (w) => w.replaceAll("ئ", "ی")],
  ["آ → ا (H7)", (w) => w.replaceAll("آ", "ا")],
  ["harakat / tanwin / shadda removed", (w) => w.replace(/[\u064B-\u065F\u0670]/g, "")],
  ["tatweel removed", (w) => w.replaceAll("\u0640", "")],
  ["Persian / Arabic digits → ASCII", (w) => w.replace(/[۰-۹]/g, (d) => String(d.charCodeAt(0) - 0x06f0)).replace(/[٠-٩]/g, (d) => String(d.charCodeAt(0) - 0x0660))],
  ["3+ repeated letters → 1", (w) => w.replace(/([ؠ-يٮ-ۓەۺ-ۿ])\1{2,}/g, "$1")],
  ["ZWNJ removed (term output)", (w) => w.replaceAll("\u200C", "")],
];

interface Group { key: string; forms: [string, number][] }

function collide(f: (w: string) => string, before: (w: string) => string = (w) => w): Group[] {
  const by = new Map<string, Map<string, [string, number][]>>();
  for (const [w, n] of vocab) {
    const k = f(w);
    const b = before(w);
    const inner = by.get(k) ?? new Map<string, [string, number][]>();
    inner.set(b, [...(inner.get(b) ?? []), [w, n]]);
    by.set(k, inner);
  }
  const groups: Group[] = [];
  for (const [key, inner] of by) {
    // A collision: forms that were apart before the rule (different "before" keys) now share a key.
    if (inner.size < 2) continue;
    groups.push({ key, forms: [...inner.values()].map((l) => l.sort((a, b) => b[1] - a[1])[0]!) });
  }
  // Rank by the frequency of the rarer side: two frequent words merging matters most.
  const weight = (g: Group) => g.forms.map(([, n]) => n).sort((a, b) => b - a)[1] ?? 0;
  return groups.sort((a, b) => weight(b) - weight(a));
}

const lines: string[] = [];
const out = (s = "") => lines.push(s);
const show = (g: Group) => `- ${g.forms.map(([w, n]) => `«${w}» ${n}`).join(" · ")} → «${g.key}»`;

if (values.diff) {
  const [a, b] = values.diff.split(",") as [string, string];
  const fa = configByName(a).analyzer!, fb = configByName(b).analyzer!;
  const ta = (w: string) => fa.analyze(w, "query").join(" "), tb = (w: string) => fb.analyze(w, "query").join(" ");
  const groups = collide(tb, ta);
  out(`# Merges ${b} adds over ${a}`);
  out();
  out(`Vocabulary forms seen ≥ ${MIN} times (${vocab.length.toLocaleString("en")}) that ${a} keeps apart and ${b} gives the same term. ${groups.length} groups; top ${TOP}, ranked by the rarer form's count.`);
  out();
  for (const g of groups.slice(0, TOP)) out(show(g));
  writeFileSync(new URL(`results/collisions-${a}--${b}.md`, import.meta.url), lines.join("\n") + "\n");
  console.log(lines.slice(0, 20).join("\n"));
} else {
  out("# Fold collisions");
  out();
  out(`Generated by \`node bench/collisions.ts\`. Vocabulary forms seen ≥ ${MIN} times in the raw sources (${vocab.length.toLocaleString("en")} forms).`);
  out("For each fold rule alone: groups of different forms it makes identical, ranked by the rarer form's count. Reviewed by hand in bench/results/experiments.md.");
  out();
  for (const [name, f] of RULES) {
    const groups = collide(f, (w) => w);
    out(`## ${name}: ${groups.length} groups`);
    out();
    for (const g of groups.slice(0, TOP)) out(show(g));
    out();
  }
  writeFileSync(new URL("results/collisions.md", import.meta.url), lines.join("\n") + "\n");
  console.log(lines.filter((l) => l.startsWith("## ")).join("\n"));
}
