/**
 * Conflation quality against hand-checked lemmas (UD Persian-Seraji and PerDT,
 * CC BY-SA, evaluation only). Independent of the query generator and of Hazm.
 *
 *     node bench/conflation.ts [--configs snowball,fa-standard,...] [--name conflation]
 *     node bench/conflation.ts --configs fa-full,lm-tree --base fa-full --splits dev --name conflation-lm-dev
 *
 * Unit: distinct (word form, gold lemma) pairs of one treebank. Paice's indices:
 * - under-stemming UI = pairs of forms with the same lemma that get different
 *   terms / all same-lemma pairs;
 * - over-stemming OI = pairs of different forms with different lemmas that get
 *   the same term / all different-lemma pairs.
 * Raw Snowball is the baseline; the analyzer has to improve on it, not just match.
 * Also lists, per config, the most frequent wrong merges it adds over the base
 * (`--base`, default Snowball), for review. `--splits` picks the UD files (default all;
 * Phase 4b tunes on dev and reads test once).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { configByName } from "./configs.ts";
import { entries, score, type Entry, type Scores } from "./lib/conflation.ts";
import { TREEBANKS } from "./lib/ud.ts";

const { values } = parseArgs({
  options: {
    configs: { type: "string", default: "snowball,fa-light,fa-standard" },
    name: { type: "string", default: "conflation" },
    examples: { type: "string", default: "25" },
    base: { type: "string", default: "snowball" },
    splits: { type: "string", default: "train,dev,test" },
  },
});
const names = ["none", ...values.configs!.split(",").filter((c) => c !== "none")];
const EXAMPLES = Number(values.examples);
const BASE = values.base!;
const SPLITS = values.splits!.split(",");
if (!names.includes(BASE)) names.splice(1, 0, BASE);

/** The term a config gives one word: the analyzer in query mode, or the bare form for "none". */
function termFn(name: string): (form: string) => string {
  if (name === "none") return (f) => f;
  const config = configByName(name);
  if (!config.analyzer) return (f) => f.toLowerCase();
  return (f) => config.analyzer!.analyze(f, "query").join(" ");
}

const lines: string[] = [];
const out = (s = "") => lines.push(s);
const json: Record<string, Record<string, Omit<Scores, "merges">>> = {};

out("# Conflation against UD gold lemmas");
out();
out(`Generated by \`node bench/conflation.ts --configs ${values.configs} --base ${BASE} --splits ${SPLITS.join(",")}\`. UD Persian-Seraji and PerDT (CC BY-SA 4.0, evaluation only), files: ${SPLITS.join(", ")}.`);
out("Unit: distinct (form, gold lemma) pairs. **UI** (under-stemming) = share of same-lemma form pairs left apart;");
out("**OI** (over-stemming) = share of different-lemma, different-form pairs merged (×10⁶ for readability).");
out("`none` = forms as written (no analysis). Seraji lemmatizes the passive «شد» as «کرد», so its verb UI has a floor.");
out();

for (const [bank, families] of TREEBANKS.flatMap((b) => [[b, false], [b, true]] as const)) {
  const list = entries(bank, families, SPLITS);
  const view = families ? `${bank}-families` : bank;
  json[view] = {};
  const scores = new Map<string, Scores>();
  for (const name of names) scores.set(name, score(list, termFn(name)));
  out(`## ${bank}${families ? ", verb families" : ", gold lemmas"} (${list.length.toLocaleString("en")} form–lemma pairs)`);
  out();
  out("| config | UI % | OI ×10⁶ | same-lemma pairs apart | wrong merges | UI NOUN | UI VERB | UI ADJ |");
  out("|---|---:|---:|---:|---:|---:|---:|---:|");
  for (const [name, s] of scores) {
    const { merges: _, ...rest } = s;
    json[view]![name] = rest;
    const pos = (p: string) => (s.byPos[p] ? (100 * s.byPos[p].umt / s.byPos[p].dmt).toFixed(1) : "–");
    out(`| ${name} | ${(100 * s.ui).toFixed(2)} | ${(1e6 * s.oi).toFixed(1)} | ${s.umt.toLocaleString("en")} | ${s.wmt.toLocaleString("en")} | ${pos("NOUN")} | ${pos("VERB")} | ${pos("ADJ")} |`);
  }
  out();
  if (!scores.has(BASE) || families) continue;
  // Wrong merges a config adds over the base: different-lemma, different-form
  // pairs it merges and the base keeps apart, grouped by the config's term.
  const baseTerm = termFn(BASE);
  for (const name of names.filter((n) => n !== "none" && n !== BASE)) {
    const s = scores.get(name)!;
    const added: { term: string; entries: Set<Entry>; pairs: number; freq: number }[] = [];
    for (const [t, group] of s.merges) {
      const involved = new Set<Entry>();
      let n = 0;
      for (let i = 0; i < group.length; i++) {
        for (let j = i + 1; j < group.length; j++) {
          const a = group[i]!, b = group[j]!;
          if (a.lemma === b.lemma || a.form === b.form || baseTerm(a.form) === baseTerm(b.form)) continue;
          involved.add(a); involved.add(b); n++;
        }
      }
      if (n) added.push({ term: t, entries: involved, pairs: n, freq: [...involved].reduce((x, e) => x + e.freq, 0) });
    }
    added.sort((a, b) => b.freq - a.freq);
    out(`### ${bank}: wrong merges ${name} adds over ${BASE} (${added.reduce((x, a) => x + a.pairs, 0)} pairs in ${added.length} terms; top ${EXAMPLES} by frequency)`);
    out();
    for (const a of added.slice(0, EXAMPLES)) {
      const by = new Map<string, string[]>();
      for (const e of a.entries) by.set(e.lemma, [...(by.get(e.lemma) ?? []), e.form]);
      out(`- «${a.term}» (${a.freq}): ${[...by].map(([l, fs]) => `${l} ← ${fs.slice(0, 4).join("، ")}`).join(" | ")}`);
    }
    out();
  }
}

mkdirSync(new URL("results/", import.meta.url), { recursive: true });
writeFileSync(new URL(`results/${values.name}.md`, import.meta.url), lines.join("\n") + "\n");
writeFileSync(new URL(`results/${values.name}.json`, import.meta.url), JSON.stringify(json, null, 1) + "\n");
console.log(lines.filter((l) => l.startsWith("|") || l.startsWith("## ")).join("\n"));
