/**
 * Phase 4b CP3: the confidence threshold τ of a trained lemma model, from dev only.
 *
 *     node bench/lemma-tau.ts lm-tree [--save]
 *
 * For each τ: conflation on UD's dev files (UI and OI per treebank, gold lemmas; the
 * gate is OI ≤ fa-full's on both), UD dev tokens fixed/broken, and pair-dev coverage
 * and false fires (the precision–coverage curve). Picks the lowest τ that passes the
 * OI gate; `--save` writes it into the model file.
 */
import { writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { createAnalyzer } from "../src/analyzer.ts";
import { lexicon } from "../src/lexicon/index.ts";
import { entries, score } from "./lib/conflation.ts";
import { udScore } from "./lib/lemma.ts";
import { TREEBANKS } from "./lib/ud.ts";
import { createLemmaLexicon } from "../scripts/lemma/wrap.ts";
import { predictorOf } from "../scripts/lemma/model.ts";
import { loadSaved, setTau } from "../scripts/lemma/saved.ts";
import { examples } from "../scripts/lemma/examples.ts";
import { pairMetrics } from "../scripts/lemma/train.ts";

const { values, positionals } = parseArgs({ allowPositionals: true, options: { save: { type: "boolean", default: false }, grid: { type: "string", default: "0,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,0.99" } } });
const name = positionals[0]!;
const saved = loadSaved(name);
const predict = predictorOf(saved.model);
const lists = TREEBANKS.map((b) => [b, entries(b, false, ["dev"])] as const);
const devPairs = examples("M+L").filter((e) => e.split === "dev");
const termOf = (lex: typeof lexicon) => { const a = createAnalyzer({ profile: "full", lexicon: lex }); return (f: string) => a.analyze(f, { mode: "query" }).join(" "); };
const conflate = (lex: typeof lexicon) => lists.map(([, list]) => score(list, termOf(lex)));
const base = conflate(lexicon);
const pct = (x: number) => (100 * x).toFixed(1);
const posUi = (s: ReturnType<typeof score>, p: string) => (s.byPos[p] ? pct(s.byPos[p].umt / s.byPos[p].dmt) : "–");

const lines = [`# ${name}: choosing τ (dev)`, "",
  `Generated by \`node bench/lemma-tau.ts ${name}\`. Model: ${saved.kind} on ${saved.source}, ${(saved.bytes / 1000).toFixed(1)} KB gzipped.`,
  "Conflation on UD's dev files (gold lemmas): UI %, OI ×10⁶ per treebank; the gate is OI ≤ fa-full's on both. UD dev tokens fixed/broken against fa-full. Pair-dev: M+L labels of dev lemmas.", "",
  `fa-full: seraji UI ${pct(base[0]!.ui)} OI ${(1e6 * base[0]!.oi).toFixed(1)}; perdt UI ${pct(base[1]!.ui)} OI ${(1e6 * base[1]!.oi).toFixed(1)} (NOUN ${posUi(base[1]!, "NOUN")}, VERB ${posUi(base[1]!, "VERB")}, ADJ ${posUi(base[1]!, "ADJ")}).`, "",
  "| τ | seraji UI | seraji OI | perdt UI | perdt OI | perdt UI NOUN | VERB | ADJ | OI gate | UD fixed | UD broken | pair coverage % | pair wrong % | pair false fires % |",
  "|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|"];
let picked: number | undefined;
for (const tau of values.grid!.split(",").map(Number)) {
  const lex = createLemmaLexicon(lexicon, predict, tau);
  const [s, p] = conflate(lex) as [ReturnType<typeof score>, ReturnType<typeof score>];
  const pass = s.oi <= base[0]!.oi && p.oi <= base[1]!.oi;
  if (pass && picked === undefined) picked = tau;
  const u = udScore(lex, ["dev"]);
  const m = pairMetrics(saved.model, devPairs, tau);
  lines.push(`| ${tau} | ${pct(s.ui)} | ${(1e6 * s.oi).toFixed(1)} | ${pct(p.ui)} | ${(1e6 * p.oi).toFixed(1)} | ${posUi(p, "NOUN")} | ${posUi(p, "VERB")} | ${posUi(p, "ADJ")} | ${pass ? "pass" : "fail"} | ${u.fixed} | ${u.broken} | ${pct(m.coverage)} | ${pct(m.wrongFire)} | ${pct(m.falseFire)} |`);
}
lines.push("", picked === undefined ? "**No τ passes the OI gate.**" : `**Picked τ = ${picked}** (the lowest that passes).`, "");
writeFileSync(new URL(`results/lemma-tau-${name}.md`, import.meta.url), lines.join("\n"));
console.log(lines.join("\n"));
if (values.save && picked !== undefined) setTau(name, picked);
