/**
 * Judge the tokenizer's rejoin rules («می روم» → «می‌روم», «کتاب ها» → «کتاب‌ها»)
 * on UD sentences (Seraji + PerDT, CC BY-SA, evaluation only). The rule list
 * mirrors bench/lib/variants.ts, so the benchmark cannot judge it by itself.
 *
 *     node bench/rejoin.ts
 *
 * - As written: the treebanks write affixes with a half-space, so a join the
 *   tokenizer makes across a real space is a false join (the vocative «ای خدا»,
 *   «لباس تر» = wet clothes).
 * - Half-space typed as space: every ZWNJ becomes a space; a restored join is
 *   one the tokenizer puts back.
 * Per affix: restored joins, joins it could have restored, and false joins.
 */
import { writeFileSync } from "node:fs";
import { normalize } from "../src/normalize.ts";
import { tokenize } from "../src/tokenize.ts";
import { loadTreebank, TREEBANKS } from "./lib/ud.ts";

interface Stat { restored: number; possible: number; falseJoins: number; falseExamples: string[] }
const stats = new Map<string, Stat>();
const stat = (k: string) => {
  let s = stats.get(k);
  if (!s) stats.set(k, (s = { restored: 0, possible: 0, falseJoins: 0, falseExamples: [] }));
  return s;
};

/** Which spaces (by offset) the tokenizer joined across. */
function joinedSpaces(text: string): Set<number> {
  const joined = new Set<number>();
  for (const t of tokenize(normalize(text))) {
    for (let i = t.start; i < t.end; i++) if (text[i] === " ") joined.add(i);
  }
  return joined;
}

/** The affix a join is about: a leading می/نمی, else the word after the space. */
const affixAt = (text: string, space: number) => {
  const before = text.slice(0, space).split(/[^\p{L}]/u).at(-1)!;
  const after = text.slice(space + 1).split(/[^\p{L}]/u)[0]!;
  return before === "می" || before === "نمی" ? `${before} …` : `… ${after}`;
};

let sentences = 0, writtenJoins = 0;
for (const bank of TREEBANKS) {
  for (const s of loadTreebank(bank)) {
    sentences++;
    let text = "";
    for (const w of s.words) text += w.form + (w.spaceAfter ? " " : "");
    // As written: any join across a real space is false.
    for (const i of joinedSpaces(text)) {
      const st = stat(affixAt(text, i));
      st.falseJoins++;
      writtenJoins++;
      if (st.falseExamples.length < 4) st.falseExamples.push(text.slice(Math.max(0, i - 20), i + 20).trim());
    }
    // Half-space typed as a space.
    const zw = new Set<number>();
    let spaced = "";
    for (const ch of text) {
      if (ch === "\u200C") { zw.add(spaced.length); spaced += " "; } else spaced += ch;
    }
    const joined = joinedSpaces(spaced);
    for (const i of zw) {
      const st = stat(affixAt(spaced, i));
      st.possible++;
      if (joined.has(i)) st.restored++;
    }
  }
}

const rows = [...stats].filter(([, s]) => s.restored + s.falseJoins > 0).sort((a, b) => b[1].restored + b[1].falseJoins - (a[1].restored + a[1].falseJoins));
const totalPossible = [...stats.values()].reduce((a, s) => a + s.possible, 0);
const totalRestored = [...stats.values()].reduce((a, s) => a + s.restored, 0);
const lines = [
  "# Rejoin rules on UD sentences",
  "",
  `Generated by \`node bench/rejoin.ts\`. ${sentences.toLocaleString("en")} sentences (Seraji + PerDT, all splits).`,
  `Half-space typed as space: ${totalRestored.toLocaleString("en")} of ${totalPossible.toLocaleString("en")} half-spaces restored (${(100 * totalRestored / totalPossible).toFixed(1)}%; most half-spaces are inside compounds, which no affix rule should join).`,
  `As written: ${writtenJoins.toLocaleString("en")} false joins across real spaces.`,
  "",
  "| affix | restored | half-spaces with this affix | false joins (as written) | precision |",
  "|---|---:|---:|---:|---:|",
  ...rows.map(([k, s]) => `| ${k} | ${s.restored} | ${s.possible} | ${s.falseJoins} | ${(100 * s.restored / (s.restored + s.falseJoins)).toFixed(1)}% |`),
  "",
  "False-join examples:",
  "",
  ...rows.filter(([, s]) => s.falseJoins).map(([k, s]) => `- ${k}: ${s.falseExamples.map((e) => `«${e}»`).join(" · ")}`),
];
writeFileSync(new URL("results/rejoin.md", import.meta.url), lines.join("\n") + "\n");
console.log(lines.slice(0, 30).join("\n"));
