/**
 * Aggregate cached runs into recall@10 / MRR@10 per corpus × variant type ×
 * engine × config.
 *
 *     node bench/report.ts [--name baseline] [--split dev|test|all] [--configs stock,snowball,fa-standard]
 *
 * Writes bench/results/<name>.json (every number, with n and 95% Wilson
 * intervals) and bench/results/<name>.md (the tables). Tuning is judged on the
 * dev split; the test split is reported once, at the end of a phase. Runs that
 * answered an older query set are skipped (and named on stderr).
 *
 * The canonical row uses only the main targets. Supplementary targets (sampled
 * to fill rare variant types) count only in their own variant rows. "Kept" is
 * the paired view: of the queries whose canonical form the config found, the
 * share it still finds after the variant.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { CONFIGS } from "./configs.ts";
import { CORPORA } from "./corpus.ts";
import { ENGINES } from "./engines.ts";
import { type Query } from "./queries.ts";
import { loadRun, macroByLemma, splitQueries, VERB_TYPES } from "./lib/results.ts";
import type { Split } from "./lib/split.ts";
import { VARIANTS } from "./lib/variants.ts";

const { values } = parseArgs({
  options: { name: { type: "string" }, split: { type: "string", default: "dev" }, configs: { type: "string" } },
});
const split = values.split as Split;
values.name ??= `report-${split}`;
const RESULTS = new URL("results/", import.meta.url);

export interface Cell {
  n: number;
  recall: number;
  recallLo: number;
  recallHi: number;
  mrr: number;
  /** Share of this type's queries found, among those whose canonical query was found (paired). */
  kept: number | null;
  /** Verb rows: recall averaged per lemma, then over lemmas. */
  lemmaMacro?: number;
  lemmas?: number;
}

/** Wilson score interval for a proportion, 95%. */
function wilson(successes: number, n: number): [number, number] {
  if (n === 0) return [0, 0];
  const z = 1.96, p = successes / n;
  const denom = 1 + (z * z) / n;
  const centre = (p + (z * z) / (2 * n)) / denom;
  const half = (z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n))) / denom;
  return [Math.max(0, centre - half), Math.min(1, centre + half)];
}

function cell(queries: Query[], rankOf: Map<string, number>): Cell {
  const ranks = queries.map((q) => rankOf.get(q.id) ?? 0);
  const found = ranks.filter((r) => r > 0).length;
  const [lo, hi] = wilson(found, ranks.length);
  let pairedBase = 0, pairedKept = 0;
  for (const q of queries) {
    if (q.type === "canonical") continue;
    if ((rankOf.get(`${q.base}/canonical`) ?? 0) === 0) continue;
    pairedBase++;
    if ((rankOf.get(q.id) ?? 0) > 0) pairedKept++;
  }
  const macro = queries.length && VERB_TYPES.has(queries[0]!.type)
    ? macroByLemma(queries, (q) => ((rankOf.get(q.id) ?? 0) > 0 ? 1 : 0)) : null;
  return {
    n: ranks.length,
    recall: ranks.length ? found / ranks.length : 0,
    recallLo: lo, recallHi: hi,
    mrr: ranks.length ? ranks.reduce((s, r) => s + (r ? 1 / r : 0), 0) / ranks.length : 0,
    kept: pairedBase ? pairedKept / pairedBase : null,
    ...(macro ? { lemmaMacro: macro.mean, lemmas: macro.lemmas } : {}),
  };
}

const types = VARIANTS.map(([t]) => t);
const engines = ENGINES.map((e) => e.name);
const configs = values.configs ? values.configs.split(",") : CONFIGS.filter((c) => !c.experiment).map((c) => c.name);
/** results[corpus][type][engine][config] */
const results: Record<string, Record<string, Record<string, Record<string, Cell>>>> = {};
const timings: Record<string, Record<string, Record<string, { buildMs: number; searchMs: number; queries: number }>>> = {};
const MIN_N = 30;

for (const corpus of CORPORA) {
  const queries = splitQueries(corpus, split);
  const byType = new Map<string, Query[]>();
  for (const q of queries) byType.set(q.type, [...(byType.get(q.type) ?? []), q]);
  results[corpus] = {};
  timings[corpus] = {};
  for (const engine of engines) {
    timings[corpus][engine] = {};
    for (const config of configs) {
      const loaded = loadRun(corpus, engine, config, split);
      if (!loaded) continue;
      const { run, rank: rankOf } = loaded;
      timings[corpus][engine][config] = { buildMs: run.buildMs, searchMs: run.searchMs, queries: run.ids.length };
      for (const type of types) {
        const qs = byType.get(type) ?? [];
        if (qs.length < MIN_N) continue;
        ((results[corpus][type] ??= {})[engine] ??= {})[config] = cell(qs, rankOf);
      }
    }
  }
}

// --- Markdown -------------------------------------------------------------------

const pct = (x: number) => (100 * x).toFixed(0);
const lines: string[] = [];
const out = (s = "") => lines.push(s);

out(`# fa-search-kit benchmark: ${values.name}`);
out();
out(`Generated by \`node bench/report.ts --name ${values.name} --split ${split}\` on ${new Date().toISOString().slice(0, 10)}. Method: [bench/README.md](../README.md).`);
out(`Split: **${split}** (${split === "all" ? "every query" : `the ${split} half of the targets, bench/lib/split.ts`}).`);
out();
out("Recall@10 in %: the share of queries whose target document is in the top 10. Each corpus has 20,000 documents;");
out("*n* is the number of queries of that type. Rows with fewer than 30 queries are left out.");
out("Configs: **stock** = engine defaults; **tuned** = the engine's closest language option + typo tolerance;");
out("**snowball** = Snowball 3.1.1 Persian stemmer plugged in naively; **fa-light / fa-standard / fa-full** = fa-search-kit's profiles through its shipped adapters; **p1-*** = the same profiles through Phase 1's bench wiring.");
out("Verb rows also get a per-lemma macro average (last section), since a few verbs (شد, می\u200Cشود) dominate them.");
out();

// Summary: mean recall over variant types (not canonical), per corpus × engine × config.
out("## Summary");
out();
out("Mean recall@10 over all variant types (each type weighted equally; canonical excluded), and canonical recall.");
out();
out(`| corpus | engine | ${configs.map((c) => `${c} variants`).join(" | ")} | ${configs.map((c) => `${c} canonical`).join(" | ")} |`);
out(`|---|---|${configs.map(() => "---:").join("|")}|${configs.map(() => "---:").join("|")}|`);
for (const corpus of CORPORA) {
  for (const engine of engines) {
    const means = configs.map((config) => {
      const cells = types.filter((t) => t !== "canonical").map((t) => results[corpus]![t]?.[engine]?.[config]).filter((c): c is Cell => !!c);
      return cells.length ? pct(cells.reduce((s, c) => s + c.recall, 0) / cells.length) : "–";
    });
    const canon = configs.map((config) => { const c = results[corpus]!.canonical?.[engine]?.[config]; return c ? pct(c.recall) : "–"; });
    out(`| ${corpus} | ${engine} | ${means.join(" | ")} | ${canon.join(" | ")} |`);
  }
}
out();

out("Same view as MRR@10 (×100): rank losses that recall@10 hides, e.g. when an OR engine still finds the target through the query's other words.");
out();
out(`| corpus | engine | ${configs.map((c) => `${c} variants`).join(" | ")} | ${configs.map((c) => `${c} canonical`).join(" | ")} |`);
out(`|---|---|${configs.map(() => "---:").join("|")}|${configs.map(() => "---:").join("|")}|`);
for (const corpus of CORPORA) {
  for (const engine of engines) {
    const means = configs.map((config) => {
      const cells = types.filter((t) => t !== "canonical").map((t) => results[corpus]![t]?.[engine]?.[config]).filter((c): c is Cell => !!c);
      return cells.length ? pct(cells.reduce((s, c) => s + c.mrr, 0) / cells.length) : "–";
    });
    const canon = configs.map((config) => { const c = results[corpus]!.canonical?.[engine]?.[config]; return c ? pct(c.mrr) : "–"; });
    out(`| ${corpus} | ${engine} | ${means.join(" | ")} | ${canon.join(" | ")} |`);
  }
}
out();

for (const corpus of CORPORA) {
  out(`## ${corpus}`);
  out();
  for (const config of configs) {
    out(`### ${corpus} · ${config}`);
    out();
    out(`| variant | n | ${engines.join(" | ")} |`);
    out(`|---|---:|${engines.map(() => "---:").join("|")}|`);
    for (const type of types) {
      const row = results[corpus]![type];
      if (!row) continue;
      const n = Object.values(row)[0]?.[config]?.n;
      if (n === undefined) continue;
      out(`| ${type} | ${n} | ${engines.map((e) => { const c = row[e]?.[config]; return c ? pct(c.recall) : "–"; }).join(" | ")} |`);
    }
    out();
  }
}

out("## Verb rows, per-lemma macro recall");
out();
out("Recall averaged within each verb lemma, then over lemmas.");
out();
out(`| corpus | type | lemmas | engine | ${configs.join(" | ")} |`);
out(`|---|---|---:|---|${configs.map(() => "---:").join("|")}|`);
for (const corpus of CORPORA) {
  for (const type of types.filter((t) => VERB_TYPES.has(t))) {
    const row = results[corpus]![type];
    if (!row) continue;
    for (const engine of engines) {
      const lemmas = Object.values(row[engine] ?? {})[0]?.lemmas;
      if (lemmas === undefined) continue;
      out(`| ${corpus} | ${type} | ${lemmas} | ${engine} | ${configs.map((c) => { const x = row[engine]?.[c]?.lemmaMacro; return x === undefined ? "–" : pct(x); }).join(" | ")} |`);
    }
  }
}
out();

out("## Timing");
out();
out("Index build and total search time for all queries of the corpus (one Node process, Apple Silicon laptop). Indicative only.");
out();
out(`| corpus | engine | ${configs.map((c) => `${c} build s`).join(" | ")} | ${configs.map((c) => `${c} ms/query`).join(" | ")} |`);
out(`|---|---|${configs.map(() => "---:").join("|")}|${configs.map(() => "---:").join("|")}|`);
for (const corpus of CORPORA) {
  for (const engine of engines) {
    const t = timings[corpus]![engine]!;
    out(`| ${corpus} | ${engine} | ${configs.map((c) => (t[c] ? (t[c].buildMs / 1000).toFixed(1) : "–")).join(" | ")} | ${configs.map((c) => (t[c] ? (t[c].searchMs / t[c].queries).toFixed(2) : "–")).join(" | ")} |`);
  }
}
out();

mkdirSync(RESULTS, { recursive: true });
writeFileSync(new URL(`${values.name}.json`, RESULTS), JSON.stringify({ generated: new Date().toISOString(), split, results, timings }, null, 1) + "\n");
writeFileSync(new URL(`${values.name}.md`, RESULTS), lines.join("\n"));
console.log(`wrote bench/results/${values.name}.{json,md}`);
