/**
 * Query rescue at a glance: per config, corpus and engine, the rows rescue is for,
 * the control row, the false-fix rate, typo-uniform and the word bytes a weak query
 * needed. For judging the Phase 3 arms side by side (the per-cell gate is compare.ts).
 *
 *     node bench/rescue-report.ts [--split dev] [--configs fa-full,fa-rescue,r1-empty,...]
 *
 * Writes bench/results/rescue-<split>.md.
 */
import { writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { CONFIGS } from "./configs.ts";
import { CORPORA } from "./corpus.ts";
import { ENGINES } from "./engines.ts";
import { loadRun, splitQueries } from "./lib/results.ts";
import { loadSet } from "./lib/rescue-sets.ts";
import { inSplit, type Split } from "./lib/split.ts";

const { values } = parseArgs({ options: { split: { type: "string", default: "dev" }, configs: { type: "string" } } });
const split = values.split as Split;
const configs = values.configs?.split(",") ?? ["fa-full", ...CONFIGS.filter((c) => c.fa?.rescue || c.fa?.native).map((c) => c.name)];
const TYPO = ["homophone", "typo-adjacent", "typo-delete", "typo-transpose"];
const LAYOUT = ["layout-isiri9147", "layout-win-legacy", "layout-mac-legacy", "layout-latin-on-fa"];
const pct = (x: number) => (Number.isNaN(x) ? "–" : (100 * x).toFixed(1));
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
const at = (xs: number[], p: number) => xs.slice().sort((a, b) => a - b)[Math.floor(p * (xs.length - 1))] ?? 0;

const lines: string[] = [];
const out = (s = "") => lines.push(s);
out(`# Query rescue, ${split} split`);
out();
out(`Generated by \`node bench/rescue-report.ts --split ${split}\`. Recall@10 in %; typo = mean over ${TYPO.join(", ")}; layout = mean over the ${LAYOUT.length} keyboard rows; `
  + "typo, one click = found as shown or in the suggestion's results; MRR on the typo rows ×100; notice = % of the rows spelled correctly (every other type) searched as a fix, suggests = % of them offered a suggestion; false fixes / false suggestions = % of the ff-* queries rewritten / offered a suggestion (all six types pooled); "
  + "KB = word bytes a weak Pagefind query needed (median / p95, gzipped, cold). Types with fewer than 10 queries are left out of the means; – = not run.");
out();
for (const corpus of CORPORA) {
  const queries = splitQueries(corpus, split);
  const typeOf = new Map(queries.map((q) => [q.id, q.type]));
  let set: ReturnType<typeof loadSet> = [];
  try { set = loadSet(corpus, "rescue").filter((q) => inSplit(q.base, split)); } catch { /* no extra set */ }
  out(`## ${corpus}`);
  out();
  out("| config | engine | canonical | typo | typo, one click | typo MRR | layout | notice | suggests | false fixes | false suggestions | typo-uniform | KB |");
  out("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|");
  for (const config of configs) {
    for (const engine of ENGINES.map((e) => e.name)) {
      const run = loadRun(corpus, engine, config, split);
      if (!run) continue;
      const rows = (types: string[], f: (r: number) => number) => mean(types.map((t) => {
        const qs = queries.filter((q) => q.type === t);
        return qs.length >= 10 ? mean(qs.map((q) => f(run.rank.get(q.id) ?? 0))) : NaN;
      }).filter((x) => !Number.isNaN(x)));
      const found = (r: number) => (r > 0 ? 1 : 0), rr = (r: number) => (r ? 1 / r : 0);
      // Found as shown, or in the suggestion's results (one click away).
      const click = (types: string[]) => mean(types.map((t) => {
        const qs = queries.filter((q) => q.type === t);
        return qs.length >= 10 ? mean(qs.map((q) => ((run.rank.get(q.id) ?? 0) > 0 || (run.suggestedRank?.get(q.id) ?? 0) > 0 ? 1 : 0))) : NaN;
      }).filter((x) => !Number.isNaN(x)));
      const correct = queries.filter((q) => q.type !== "canonical" && !TYPO.includes(q.type) && !LAYOUT.includes(q.type));
      const notice = run.fixed ? pct(correct.filter((q) => run.fixed!.get(q.id)).length / correct.length) : "0";
      const suggests = run.suggested ? pct(correct.filter((q) => run.suggested!.get(q.id)).length / correct.length) : "–";
      const s = loadRun(corpus, engine, config, split, "rescue");
      const ff = set.filter((q) => q.type.startsWith("ff-")), uni = set.filter((q) => q.type === "typo-uniform");
      const falseFix = !s ? "–" : s.fixed ? pct(ff.filter((q) => s.fixed!.get(q.id)).length / ff.length) : "0";
      const falseSuggest = !s ? "–" : s.suggested ? pct(ff.filter((q) => s.suggested!.get(q.id)).length / ff.length) : "–";
      const uniform = !s || !uni.length ? "–" : pct(uni.filter((q) => (s.rank.get(q.id) ?? 0) > 0).length / uni.length);
      const bytes = run.bytes ? [...run.bytes].filter(([id, b]) => b > 0 && typeOf.has(id)).map(([, b]) => b) : [];
      const kb = bytes.length ? `${(at(bytes, 0.5) / 1024).toFixed(1)} / ${(at(bytes, 0.95) / 1024).toFixed(1)}` : "–";
      out(`| ${config} | ${engine} | ${pct(rows(["canonical"], found))} | ${pct(rows(TYPO, found))} | ${run.suggested ? pct(click(TYPO)) : "–"} | ${pct(rows(TYPO, rr))} | ${pct(rows(LAYOUT, found))} | ${notice} | ${suggests} | ${falseFix} | ${falseSuggest} | ${uniform} | ${kb} |`);
    }
  }
  out();
}
const file = new URL(`results/rescue-${split}.md`, import.meta.url);
writeFileSync(file, lines.join("\n"));
console.log(`wrote ${file.pathname.split("/fa-search/")[1]}`);
