/**
 * Build the lemma model's training data and (Phase 4b CP6, if it ships) src/lemma/data.ts.
 *
 *     node scripts/build-lemma.ts --mine      # bench/data/lemma/mined.jsonl (label source M) + a report
 *
 * Label sources (bench/results/experiments.md, "Phase 4b"): M mined from Hazm's
 * verbs and our vocabulary counts (scripts/lemma/pairs.ts); L the two-family LLM
 * labels of our own word list (bench/lemma-llm.ts); U and H, UD gold and Hazm's
 * lemmatizer, comparison only. Every pair carries its lemma, and the split is by
 * lemma (bench/lib/lemma.ts), frozen before any labelling.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { lemmaSplit, udExamples, udScore } from "../bench/lib/lemma.ts";
import { lexicon } from "../src/lexicon/index.ts";
import { createLemmaLexicon } from "./lemma/wrap.ts";
import { predictorOf } from "./lemma/model.ts";
import { saveModel } from "./lemma/saved.ts";
import { nominalPairs, verbPairs, type Pair } from "./lemma/pairs.ts";
import { examples, type Source } from "./lemma/examples.ts";
import { gzipBytes, type Model } from "./lemma/model.ts";
import { pairMetrics, train } from "./lemma/train.ts";

const { values } = parseArgs({
  options: {
    mine: { type: "boolean", default: false },
    train: { type: "boolean", default: false }, kind: { type: "string", default: "tree" }, source: { type: "string", default: "M+L" },
    kb: { type: "string", default: "25" }, name: { type: "string" }, tau: { type: "string", default: "0" }, heldout: { type: "string" },
    sweep: { type: "boolean", default: false }, emit: { type: "string" }, sources: { type: "string", default: "M+L" }, kinds: { type: "string", default: "tree,linear,list" }, kbs: { type: "string", default: "5,10,25,50" },
  },
});
export const LEMMA_DIR = new URL("../bench/data/lemma/", import.meta.url);
/** Mined-only bar (the plan): a class's UD-checked fires must be ≥ 90% right, on ≥ 30 checks. */
const BAR = 0.9, MIN_CHECKS = 30;

if (values.mine) {
  mkdirSync(LEMMA_DIR, { recursive: true });
  const pairs = [...verbPairs(), ...nominalPairs()];
  const { text, failing } = report(pairs);
  // Classes below the bar are dropped, not fixed later: their fires go to the LLM queue.
  for (const p of pairs) if (p.target && !p.unsure && failing.has(p.cls)) p.unsure = true;
  writeFileSync(new URL("mined.jsonl", LEMMA_DIR), pairs.map((p) => JSON.stringify({ ...p, split: lemmaSplit(p.lemma) })).join("\n") + "\n");
  writeFileSync(new URL("../bench/results/lemma-mined.md", import.meta.url), text);
  console.log(`classes below the bar (fires → LLM queue): ${[...failing].join(", ")}`);
  console.log(`mined ${pairs.length} pairs; wrote bench/data/lemma/mined.jsonl and bench/results/lemma-mined.md`);
}

/**
 * Mined labels against UD gold where the words overlap: a word's UD answer is its
 * dominant target (≥ 90% of its content-word uses). A fire is right when it gives
 * that target; a defer is right when fa-full already does.
 */
function report(pairs: Pair[]): { text: string; failing: Set<string> } {
  const ud = new Map<string, Map<string, number>>();
  for (const e of udExamples()) {
    const m = ud.get(e.word) ?? new Map();
    m.set(`${e.target}\t${e.base}`, (m.get(`${e.target}\t${e.base}`) ?? 0) + e.count);
    ud.set(e.word, m);
  }
  const udAnswer = (w: string) => {
    const m = ud.get(w);
    if (!m) return undefined;
    const all = [...m].sort((a, b) => b[1] - a[1]);
    const total = all.reduce((s, x) => s + x[1], 0);
    if (all[0]![1] < 0.9 * total) return undefined;
    const [target, base] = all[0]![0].split("\t") as [string, string];
    return { target, base };
  };
  const lines = ["# Mined lemma labels (label source M)", "",
    "Generated by `node scripts/build-lemma.ts --mine` (scripts/lemma/pairs.ts). Fire = the label gives a term; defer = fa-full's term stands.",
    "UD check: words also in UD (either treebank) whose uses agree on one target (≥ 90%); a fire is right when it gives UD's target, a defer when fa-full already does.", "",
    "| class | fire | defer | unsure | split train/dev/test (pairs) | UD-checked fires | right % | UD-checked defers | right % |",
    "|---|---:|---:|---:|---|---:|---:|---:|---:|"];
  const classes = [...new Set(pairs.map((p) => p.cls.replace(/^(?:lookalike|unsure) /, "")))];
  const pct = (a: number, b: number) => (b ? (100 * a / b).toFixed(1) : "–");
  const wrongFires: string[] = [];
  const failing = new Set<string>();
  for (const cls of classes) {
    const ps = pairs.filter((p) => p.cls.replace(/^(?:lookalike|unsure) /, "") === cls);
    const fire = ps.filter((p) => p.target && !p.unsure), defer = ps.filter((p) => !p.target), unsure = ps.filter((p) => p.unsure);
    const sp = (s: string) => ps.filter((p) => lemmaSplit(p.lemma) === s).length;
    let fc = 0, fr = 0, dc = 0, dr = 0;
    for (const p of fire) {
      const a = udAnswer(p.word);
      if (!a) continue;
      fc++;
      if (a.target === p.target) fr++;
      else wrongFires.push(`«${p.word}» → ${p.target}, UD ${a.target} (${cls}, ${p.count})`);
    }
    for (const p of defer) {
      const a = udAnswer(p.word);
      if (!a) continue;
      dc++;
      if (a.target === a.base) dr++;
    }
    if (fire.length && (fc < MIN_CHECKS || fr < BAR * fc)) failing.add(cls);
    lines.push(`| ${cls} | ${fire.length} | ${defer.length} | ${unsure.length} | ${sp("train")}/${sp("dev")}/${sp("test")} | ${fc} | ${pct(fr, fc)} | ${dc} | ${pct(dr, dc)} |`);
  }
  lines.push("", `Classes below the bar (${100 * BAR}% of ≥ ${MIN_CHECKS} UD-checked fires): ${[...failing].join(", ")}. Their fires are not M labels; they go to the LLM labellers' queue.`);
  lines.push("", `Fires UD disagrees with (${wrongFires.length}; by count):`, "", wrongFires.sort((a, b) => Number(b.match(/(\d+)\)$/)![1]) - Number(a.match(/(\d+)\)$/)![1])).slice(0, 120).join(" · "), "");
  return { text: lines.join("\n"), failing };
}

const pct = (x: number) => (100 * x).toFixed(1);

if (values.train) {
  const kind = values.kind as Model["kind"], source = values.source as Source, budget = 1000 * Number(values.kb);
  const without = values.heldout ? (await import("../bench/configs.ts")).heldOutVerbs(values.heldout as "dev" | "test") : undefined;
  const r = train(kind, source, budget, { without });
  const name = values.name ?? `lm-${kind}`;
  saveModel({ name, kind, source, budget, options: r.options, tau: Number(values.tau), data: r.model.data }, r.words);
  console.log(`${name}: ${kind} on ${source}, ${gzipBytes(r.model.data)} bytes gzipped, ${JSON.stringify(r.options)}`);
}

/**
 * Offline sweep: every model family × label source × size, on pair-dev (the M+L dev
 * lemmas: unseen words) and UD dev (tokens fixed/broken against fa-full).
 */
if (values.sweep) {
  const dev = examples("M+L").filter((e) => e.split === "dev");
  const lines = ["# Lemma models offline (dev)", "",
    `Generated by \`node scripts/build-lemma.ts --sweep --sources ${values.sources} --kinds ${values.kinds} --kbs ${values.kbs}\`. τ = 0 (every prediction fires).`,
    "Pair-dev: the M+L labels of dev lemmas (words never trained on). Coverage = merges predicted exactly; wrong = merges with another edit; false fires = defers the model fires on.",
    "UD dev: tokens of UD's dev files whose term the model fixes / breaks against fa-full (coverage = fixed / fa-full's misses, false fires = broken / fa-full's hits).", "",
    "| source | model | KB (gzip) | pair coverage % | pair wrong % | pair false fires % | UD fixed | UD broken | UD coverage % | UD false fires % |",
    "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|"];
  for (const source of values.sources!.split(",") as Source[]) {
    for (const kind of values.kinds!.split(",") as Model["kind"][]) {
      for (const kb of values.kbs!.split(",").map(Number)) {
        let r: ReturnType<typeof train>;
        try { r = train(kind, source, kb * 1000); } catch (e) {
          const row = `| ${source} | ${kind} | > ${kb} | – | – | – | – | – | – | – |`;
          lines.push(row); console.log(row, (e as Error).message);
          continue;
        }
        const m = pairMetrics(r.model, dev);
        const u = udScore(createLemmaLexicon(lexicon, predictorOf(r.model)), ["dev"]);
        const row = `| ${source} | ${kind} | ${(gzipBytes(r.model.data) / 1000).toFixed(1)} | ${pct(m.coverage)} | ${pct(m.wrongFire)} | ${pct(m.falseFire)} | ${u.fixed} | ${u.broken} | ${pct(u.fixed / u.miss)} | ${pct(u.broken / u.hit)} |`;
        lines.push(row);
        console.log(row);
      }
    }
  }
  writeFileSync(new URL("../bench/results/lemma-models.md", import.meta.url), lines.join("\n") + "\n");
}

/**
 * `--emit <model>`: the chosen list as lexicon data, src/lexicon/lemmas.ts. Entries the
 * base lexicon decides anyway (its words and verbs) and PROTECTED words are left out, so
 * the shipped lexicon gives exactly the tested arm's terms (checked below on every
 * vocabulary word under the analyzer settings the adapters use).
 */
if (values.emit) {
  const { loadSaved } = await import("./lemma/saved.ts");
  const { parseEdit, DEFER } = await import("./lemma/edit.ts");
  const { PROTECTED } = await import("../src/words.ts");
  const { createLexicon } = await import("../src/lexicon/index.ts");
  const { VERBS, KEEP, PLURALS } = await import("../src/lexicon/data.ts");
  const { createAnalyzer } = await import("../src/analyzer.ts");
  const { vocab } = await import("./lib/mine.ts");
  // The base without lemmas: what the arm was tested on (the shipped `lexicon` may include them already).
  const plain = createLexicon(VERBS, KEEP, PLURALS);
  const saved = loadSaved(values.emit);
  if (saved.kind !== "list") throw new Error("--emit takes a list model");
  const [head, ...lines] = saved.data.split("\n") as [string, ...string[]];
  const labels = head.split(";").map((l) => l.replaceAll("/", "|"));
  const groups = new Map<number, string[]>();
  const inertWords: string[] = [];
  let dropped = 0;
  for (const line of lines) {
    const c = line.indexOf(":");
    const y = Number(line.slice(0, c));
    const e = parseEdit(labels[y]!);
    for (const w of line.slice(c + 1).split(",")) {
      const base = plain.terms.has(w) || plain.verb(w, true) !== undefined || (!e.verb && PROTECTED.has(w));
      // An edit that replaces the whole word (a broken plural, «ابیات» → بیت) never fired in the
      // tested arm (applyEdit keeps at least one letter); left out so the shipped lexicon is the tested one.
      const inert = w.length - e.p.length - e.k < 1;
      if (base || inert || labels[y] === DEFER) { dropped++; if (inert) inertWords.push(w); continue; }
      groups.set(y, [...(groups.get(y) ?? []), w]);
    }
  }
  // Relabel densely: only the edits still used.
  const used = [...groups.keys()].sort((a, b) => a - b);
  const data = used.map((y) => labels[y]!.replaceAll("|", "/")).join(";") + "\n" + used.map((y, i) => `${i}:${groups.get(y)!.sort().join(",")}`).join("\n");
  writeFileSync(new URL("../src/lexicon/lemmas.ts", import.meta.url),
    `/**\n * Generated by scripts/build-lemma.ts --emit ${values.emit}; do not edit.\n` +
    ` * Inflected forms the rules miss («نویسندگان», «نظامیان», comparatives, verbs outside the verb list),\n` +
    ` * as edits from word to term. Labels: two LLM families agreeing on words of our own\n` +
    ` * vocabulary list, plus rules over Hazm's verbs (bench/results/experiments.md, Phase 4b).\n` +
    ` * First line: the edits (verb or nominal / prefix / letters cut / appended); then\n` +
    ` * \`edit:word,word,…\`, words without ZWNJ.\n */\nexport const LEMMAS = ${JSON.stringify(data)};\n`);
  console.log(`emitted ${[...groups.values()].reduce((s, g) => s + g.length, 0)} words (${dropped} left out: the base lexicon's, and ${inertWords.length} whole-word replacements: ${inertWords.join(" ")}), ${used.length} edits, ${gzipBytes(data)} bytes gzipped`);
  // Equivalence: the shipped lexicon against the tested arm, on every vocabulary word.
  const { LEMMAS } = await import(`../src/lexicon/lemmas.ts?${Date.now()}`);
  const shipped = createLexicon(VERBS, KEEP, PLURALS, LEMMAS);
  const tested = createLemmaLexicon(plain, predictorOf(saved.model), saved.tau);
  let words = 0, diff = 0;
  for (const opts of [{}, { negation: "merge" as const }, { verbs: "stem" as const }]) {
    const a = createAnalyzer({ profile: "full", lexicon: shipped, ...opts }), b = createAnalyzer({ profile: "full", lexicon: tested, ...opts });
    for (const w of vocab.keys()) {
      words++;
      const x = a.analyze(w, { mode: "index" }).join(" "), y = b.analyze(w, { mode: "index" }).join(" ");
      if (x !== y && diff++ < 10) console.log(`differs: «${w}» ${JSON.stringify(opts)}: shipped ${x}, tested ${y}`);
    }
  }
  console.log(`equivalence: ${diff} of ${words} analyses differ`);
  if (diff) process.exitCode = 1;
}
