/**
 * Word lists in the core bundle. Generated by scripts/build-lexicon.ts; do not edit.
 * Kept to a few hundred bytes: the core budget is 5 KB gzipped, Snowball included.
 */

/** Words that start with می but are not verbs; "*" marks a prefix entry. */
export const MI_EXCEPTIONS = new Set("میلا* میلی* میکرو* میانی میدانی میزبانی میعانات میکی مینی میزوری میامی میرزایی میلگرد میبد میخی میسیسیپی میناکاری میانجی میاندشت میثم میرزای میدانهای میقولی مینودشت میتسوبیشی مینوی میزانی میرآباد مینیاتوری میری میمند میانجیگری میهنی میراثی میازاکی میسوری میتوکندری میابد میجی میهمانی میرعماد مینای میرباقری میرداماد میلواکی میرعلی".split(" "));

/**
 * Frequent words Snowball over-stems into another frequent word (مهمان → مهم),
 * plus its آ-spelled ان exceptions as they read once آ is folded (اسمان, not اسم).
 */
export const PROTECTED = new Set("اذربایجان اتشفشان اسمان المان مهمان میهمان سده هفته عملیات دسته پرونده محدوده مالیات فرمان شیرین رده هسته تخته بنیان سازنده بادام شاهین مجازات".split(" "));
